### ISSUE TITLE
Ringing in a continuous loop

### ISSUE THREAD

**Issue by sbillaudelle** [comakingspace/DoorBell#1]
A few days back I entered the space and was greeted by the horrifying sound of the doorbell – being played back in a neverending loop.

I unplugged the connector from the control box as a temporary fix.

**Comment by NitramLegov** [comment]
I heard about it yesterday and checked a few things.
Apparently either the external pull-up (1.4kOhm) or the anti-interference capacitor was broken. I removed the capacitor and replaced the resistor. Now the doorbell is not ringing in a loop anymore. However, it is now ringing at random times, so it's not that much better.

Therefore, I think we will need a capacitor again. Last time I think we just picked a random one that was available. Do we need to discuss the values of the capacitor first?

Additionally, we should probably disable the internal pullup of the esp as well, since we're using an external one.

**Comment by NitramLegov** [comment]
I put in a new capacitor. This seems to have fixed the issue entirely.
We should keep an eye on this. If it happens again, we need to check, why components seem to break.

In addition, I changed the MQTT implementation to PubSubClient. Therefore, our MQTT issues should hopefully be gone. With this, the randomization of the ringtones should also work now.
